/**
 * Hook para gerenciar pedidos enviados para aprovação
 * Persiste no Supabase na tabela 'pedidos_aprovacao'
 * 
 * SESSÃO DIÁRIA:
 * - Pedidos pendentes: persistem indefinidamente até decisão
 * - Pedidos aprovados/rejeitados/cancelados: válidos apenas no dia da criação
 * - No carregamento do app, pedidos finalizados de dias anteriores são removidos
 */

import { useState, useCallback, useEffect, useMemo } from 'react';
import type { PedidoAprovacao } from '../lib/types';
import { supabase } from '../lib/supabase';
import { invalidateDataLakeCache } from '../lib/api/mockDataLake';

/** Retorna o timestamp do início do dia atual (00:00:00.000) */
function getStartOfTodayISO(): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  return d.toISOString();
}

export function usePedidosAprovacao() {
  const [pedidos, setPedidos] = useState<PedidoAprovacao[]>([]);
  const [loading, setLoading] = useState(true);

  // Carrega e limpa pedidos obsoletos na inicialização
  useEffect(() => {
    async function load() {
      try {
        setLoading(true);
        const { data, error } = await supabase
          .from('pedidos_aprovacao')
          .select('*')
          .order('criado_em', { ascending: false });
        
        if (error) throw error;
        
        const loaded: PedidoAprovacao[] = [];
        const idsToDelete: string[] = [];
        const startOfToday = getStartOfTodayISO();

        for (const row of (data || [])) {
          const isPendente = row.status === 'pendente';
          const isCreatedToday = row.criado_em >= startOfToday;
          
          if (isPendente || isCreatedToday) {
            loaded.push({
              id: row.id,
              criadoEm: row.criado_em,
              status: row.status as any,
              fornecedorNome: row.fornecedor,
              totalValorPedidos: row.total_valor ? Number(row.total_valor) : 0,
              // Restore JSON lists
              kpis: row.kpis,
              itens: row.itens,
              // Recompute simple aggregates to conform to interface
              totalSkus: Array.isArray(row.itens) ? row.itens.length : 0,
              totalQuantidade: Array.isArray(row.itens) ? row.itens.reduce((a: number, b: any) => a + (b.totalQuantidade || 0), 0) : 0
            } as PedidoAprovacao);
          } else {
            // Obsolete finished orders from past days
            idsToDelete.push(row.id);
          }
        }

        // Delete obsolete ones asynchronously
        if (idsToDelete.length > 0) {
          supabase.from('pedidos_aprovacao').delete().in('id', idsToDelete).then();
        }

        setPedidos(loaded);
      } catch (e) {
        console.error('Erro ao carregar pedidos_aprovacao:', e);
      } finally {
        setLoading(false);
      }
    }
    load();
  }, []);

  /** Pedidos ativos do dia: pendentes + aprovados (afetam projeções de estoque) */
  const pedidosAtivos = useMemo(() =>
    pedidos.filter(p => p.status === 'pendente' || p.status === 'aprovado'),
    [pedidos]
  );

  const adicionarPedido = useCallback(async (pedido: PedidoAprovacao) => {
    // Optimistic UI update
    setPedidos(prev => [pedido, ...prev]);

    const { error } = await supabase.from('pedidos_aprovacao').insert({
      id: pedido.id, // optional if generated by Supabase, but we can pass UUID or let DB generate
      criado_em: pedido.criadoEm,
      status: pedido.status,
      total_valor: pedido.totalValorPedidos,
      fornecedor: pedido.fornecedorNome,
      kpis: pedido.kpis,
      itens: pedido.itens
    });
    
    if (error) console.error('Erro ao inserir pedido:', error);
  }, []);

  const atualizarStatus = useCallback(async (id: string, status: 'aprovado' | 'rejeitado' | 'cancelado') => {
    // Optimistic update
    setPedidos(prev => prev.map(p => (p.id === id ? { ...p, status } : p)));

    const { error } = await supabase.from('pedidos_aprovacao').update({ status }).eq('id', id);
    if (!error) invalidateDataLakeCache();
    if (error) console.error('Erro ao atualizar status:', error);
  }, []);

  const removerPedido = useCallback(async (id: string) => {
    setPedidos(prev => prev.filter(p => p.id !== id));
    
    const { error } = await supabase.from('pedidos_aprovacao').delete().eq('id', id);
    if (!error) invalidateDataLakeCache();
    if (error) console.error('Erro ao remover pedido:', error);
  }, []);

  return { pedidos, pedidosAtivos, loading, adicionarPedido, atualizarStatus, removerPedido };
}
